//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aztuKonfrans2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aztuKonfrans2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ICEST.
        /// </summary>
        public static string about_conf {
            get {
                return ResourceManager.GetString("about_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conference is to discuss the actual problems of the universities of Azerbaijan and Turkey in the fields of education, science and technology, to identify their prospectives and summarize the scientific research updates in these areas..
        /// </summary>
        public static string about_txt_1 {
            get {
                return ResourceManager.GetString("about_txt_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conference is organize by close help of the partners of Ministry of Education of the Republic of Azerbaijan, Council of Higher Education of the Republic of Turkey, Turkish Cooperation and Coordination Agency, Azerbaijan Technical University.
        /// </summary>
        public static string about_txt_2 {
            get {
                return ResourceManager.GetString("about_txt_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The practical significance of the conference is to further enhance cooperation between the universities of Azerbaijan and Turkey and strengthen the mutual ties in the areas of education, science and technology..
        /// </summary>
        public static string about_txt_3 {
            get {
                return ResourceManager.GetString("about_txt_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string accom {
            get {
                return ResourceManager.GetString("accom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve User.
        /// </summary>
        public static string activate_user {
            get {
                return ResourceManager.GetString("activate_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string activity {
            get {
                return ResourceManager.GetString("activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline For Electronic Version Of Articles.
        /// </summary>
        public static string activity_1 {
            get {
                return ResourceManager.GetString("activity_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending The Conference Program And Placing Them On Web Site:  www.az-tr-conference2019.com.
        /// </summary>
        public static string activity_2 {
            get {
                return ResourceManager.GetString("activity_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works For The Plenary And Sectional Sessions Of The Conference.
        /// </summary>
        public static string activity_3 {
            get {
                return ResourceManager.GetString("activity_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD ANOTHER AUTHOR.
        /// </summary>
        public static string add_author {
            get {
                return ResourceManager.GetString("add_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Papers.
        /// </summary>
        public static string all_papers {
            get {
                return ResourceManager.GetString("all_papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string all_users {
            get {
                return ResourceManager.GetString("all_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string announcement {
            get {
                return ResourceManager.GetString("announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANOTHER AUTHOR&apos;S INFORMATION.
        /// </summary>
        public static string another_author {
            get {
                return ResourceManager.GetString("another_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Papers.
        /// </summary>
        public static string approved_papers {
            get {
                return ResourceManager.GetString("approved_papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Secretary of the Conference, Associate Professor Islam Islamov.
        /// </summary>
        public static string assis_secretary_1 {
            get {
                return ResourceManager.GetString("assis_secretary_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Secretary of the Conference, Associate Professor Marziya Aghayeva.
        /// </summary>
        public static string assis_secretary_2 {
            get {
                return ResourceManager.GetString("assis_secretary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTACH YOUR FILE.
        /// </summary>
        public static string attach_file {
            get {
                return ResourceManager.GetString("attach_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHOR&apos;S INFORMATION.
        /// </summary>
        public static string auth_info {
            get {
                return ResourceManager.GetString("auth_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users From Azerbaijan Who Sent The Paper.
        /// </summary>
        public static string az_paper_users {
            get {
                return ResourceManager.GetString("az_paper_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Technical University.
        /// </summary>
        public static string azTU {
            get {
                return ResourceManager.GetString("azTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Technical University, Huseyn Javid Ave. 25, Baku, Azerbaijan.
        /// </summary>
        public static string azTU_address {
            get {
                return ResourceManager.GetString("azTU_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Login.
        /// </summary>
        public static string back_login {
            get {
                return ResourceManager.GetString("back_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call for Papers.
        /// </summary>
        public static string call_papers {
            get {
                return ResourceManager.GetString("call_papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairs of the Conference.
        /// </summary>
        public static string chairs {
            get {
                return ResourceManager.GetString("chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Vilayat Valiyev – Rector of Azerbaijan Technical University.
        /// </summary>
        public static string chairs_1 {
            get {
                return ResourceManager.GetString("chairs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Dr. M. Mehmet Karaca – Rector of Istanbul Technical University.
        /// </summary>
        public static string chairs_2 {
            get {
                return ResourceManager.GetString("chairs_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE FILE.
        /// </summary>
        public static string choose_file {
            get {
                return ResourceManager.GetString("choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee.
        /// </summary>
        public static string committee {
            get {
                return ResourceManager.GetString("committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committees.
        /// </summary>
        public static string committees {
            get {
                return ResourceManager.GetString("committees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st International Scientific-Practical Conferenence.
        /// </summary>
        public static string conf_info_1 {
            get {
                return ResourceManager.GetString("conf_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December 18-20, 2019.
        /// </summary>
        public static string conf_info_2 {
            get {
                return ResourceManager.GetString("conf_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Materials.
        /// </summary>
        public static string conference_material {
            get {
                return ResourceManager.GetString("conference_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 20, 2019.
        /// </summary>
        public static string date_1 {
            get {
                return ResourceManager.GetString("date_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 30, 2019.
        /// </summary>
        public static string date_2 {
            get {
                return ResourceManager.GetString("date_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December 18–20, 2019.
        /// </summary>
        public static string date_3 {
            get {
                return ResourceManager.GetString("date_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string dates {
            get {
                return ResourceManager.GetString("dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate User.
        /// </summary>
        public static string deactivate_user {
            get {
                return ResourceManager.GetString("deactivate_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have missed the deadline! The deadline for submissions was 20 November..
        /// </summary>
        public static string deadline_text {
            get {
                return ResourceManager.GetString("deadline_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string dear {
            get {
                return ResourceManager.GetString("dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Degree.
        /// </summary>
        public static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhD.
        /// </summary>
        public static string degree_1 {
            get {
                return ResourceManager.GetString("degree_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor of Science.
        /// </summary>
        public static string degree_2 {
            get {
                return ResourceManager.GetString("degree_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        public static string degree_3 {
            get {
                return ResourceManager.GetString("degree_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Paper.
        /// </summary>
        public static string delete_paper {
            get {
                return ResourceManager.GetString("delete_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait Until The Staff Activate Your Account!.
        /// </summary>
        public static string disactive_account {
            get {
                return ResourceManager.GetString("disactive_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        public static string disapprove {
            get {
                return ResourceManager.GetString("disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Paper.
        /// </summary>
        public static string edit_paper {
            get {
                return ResourceManager.GetString("edit_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string edit_profile {
            get {
                return ResourceManager.GetString("edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information was edited successfully!.
        /// </summary>
        public static string edit_success {
            get {
                return ResourceManager.GetString("edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Is Already Exist! Please Write Another Email!.
        /// </summary>
        public static string email_exists {
            get {
                return ResourceManager.GetString("email_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that page can&apos;t be found..
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Secretaries.
        /// </summary>
        public static string ex_secretary {
            get {
                return ResourceManager.GetString("ex_secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assoc. Prof. Islam Islamov – Director of Science and Innovation Department at Azerbaijan Technical University.
        /// </summary>
        public static string ex_secretary_1 {
            get {
                return ResourceManager.GetString("ex_secretary_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assoc. Prof. Marziya Aghayeva – Director of International Relations Department at Azerbaijan Technical University.
        /// </summary>
        public static string ex_secretary_2 {
            get {
                return ResourceManager.GetString("ex_secretary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.i..
        /// </summary>
        public static string for_instance {
            get {
                return ResourceManager.GetString("for_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register for paper submission.
        /// </summary>
        public static string for_registration {
            get {
                return ResourceManager.GetString("for_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string forgot_pass {
            get {
                return ResourceManager.GetString("forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a little.
        /// </summary>
        public static string form_after {
            get {
                return ResourceManager.GetString("form_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        public static string guidelines {
            get {
                return ResourceManager.GetString("guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorary Chairs of the Conference.
        /// </summary>
        public static string honorary_chairs {
            get {
                return ResourceManager.GetString("honorary_chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeyhun Bayramov – Minister of Education of the Republic of Azerbaijan.
        /// </summary>
        public static string honorary_chairs_1 {
            get {
                return ResourceManager.GetString("honorary_chairs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Dr. M. A. Yekta Saraç – President of the Council of Higher Education of the Republic of Turkey.
        /// </summary>
        public static string honorary_chairs_2 {
            get {
                return ResourceManager.GetString("honorary_chairs_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Dates.
        /// </summary>
        public static string imp_dates {
            get {
                return ResourceManager.GetString("imp_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Information Of Users Whose Paper Is Approved.
        /// </summary>
        public static string infAppUser {
            get {
                return ResourceManager.GetString("infAppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of institution.
        /// </summary>
        public static string institution {
            get {
                return ResourceManager.GetString("institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More Papers.
        /// </summary>
        public static string load_paper {
            get {
                return ResourceManager.GetString("load_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string log_out {
            get {
                return ResourceManager.GetString("log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Admin.
        /// </summary>
        public static string make_admin {
            get {
                return ResourceManager.GetString("make_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string middle_name {
            get {
                return ResourceManager.GetString("middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        public static string my_info {
            get {
                return ResourceManager.GetString("my_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Papers.
        /// </summary>
        public static string my_papers {
            get {
                return ResourceManager.GetString("my_papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string next_page {
            get {
                return ResourceManager.GetString("next_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Paper Of This User To Show.
        /// </summary>
        public static string no_paper {
            get {
                return ResourceManager.GetString("no_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Approved Papers.
        /// </summary>
        public static string non_approved_papers {
            get {
                return ResourceManager.GetString("non_approved_papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Approved Users.
        /// </summary>
        public static string non_approved_users {
            get {
                return ResourceManager.GetString("non_approved_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Approved Yet.
        /// </summary>
        public static string not_approved {
            get {
                return ResourceManager.GetString("not_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Find Your Account!.
        /// </summary>
        public static string not_find_account {
            get {
                return ResourceManager.GetString("not_find_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing Committee by Azerbaijan Universities.
        /// </summary>
        public static string org_az {
            get {
                return ResourceManager.GetString("org_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Aviation Academy.
        /// </summary>
        public static string org_az_1 {
            get {
                return ResourceManager.GetString("org_az_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumgait State University.
        /// </summary>
        public static string org_az_10 {
            get {
                return ResourceManager.GetString("org_az_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan University of Languages.
        /// </summary>
        public static string org_az_11 {
            get {
                return ResourceManager.GetString("org_az_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Pedagogical University.
        /// </summary>
        public static string org_az_12 {
            get {
                return ResourceManager.GetString("org_az_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Slavic University.
        /// </summary>
        public static string org_az_13 {
            get {
                return ResourceManager.GetString("org_az_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Higher Oil School.
        /// </summary>
        public static string org_az_14 {
            get {
                return ResourceManager.GetString("org_az_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy of Public Administration.
        /// </summary>
        public static string org_az_15 {
            get {
                return ResourceManager.GetString("org_az_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State University of Culture and Arts.
        /// </summary>
        public static string org_az_16 {
            get {
                return ResourceManager.GetString("org_az_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Academy of Physical Education and Sport.
        /// </summary>
        public static string org_az_17 {
            get {
                return ResourceManager.GetString("org_az_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Tourism and Management University.
        /// </summary>
        public static string org_az_18 {
            get {
                return ResourceManager.GetString("org_az_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Marine Academy.
        /// </summary>
        public static string org_az_19 {
            get {
                return ResourceManager.GetString("org_az_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA University.
        /// </summary>
        public static string org_az_2 {
            get {
                return ResourceManager.GetString("org_az_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Agricultural University.
        /// </summary>
        public static string org_az_20 {
            get {
                return ResourceManager.GetString("org_az_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Technological University.
        /// </summary>
        public static string org_az_21 {
            get {
                return ResourceManager.GetString("org_az_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lankaran State University.
        /// </summary>
        public static string org_az_22 {
            get {
                return ResourceManager.GetString("org_az_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganja State University.
        /// </summary>
        public static string org_az_23 {
            get {
                return ResourceManager.GetString("org_az_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingachevir State University.
        /// </summary>
        public static string org_az_24 {
            get {
                return ResourceManager.GetString("org_az_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakhchivan State University.
        /// </summary>
        public static string org_az_25 {
            get {
                return ResourceManager.GetString("org_az_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakhchivan Teachers Institute.
        /// </summary>
        public static string org_az_26 {
            get {
                return ResourceManager.GetString("org_az_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku branch of I.M. Sechenov First Moscow State Medical University.
        /// </summary>
        public static string org_az_27 {
            get {
                return ResourceManager.GetString("org_az_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Business University.
        /// </summary>
        public static string org_az_28 {
            get {
                return ResourceManager.GetString("org_az_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan University.
        /// </summary>
        public static string org_az_29 {
            get {
                return ResourceManager.GetString("org_az_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Branch of Lomonosov Moscow State University.
        /// </summary>
        public static string org_az_3 {
            get {
                return ResourceManager.GetString("org_az_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khazar University.
        /// </summary>
        public static string org_az_30 {
            get {
                return ResourceManager.GetString("org_az_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odlar Yurdu University.
        /// </summary>
        public static string org_az_31 {
            get {
                return ResourceManager.GetString("org_az_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Eurasian University.
        /// </summary>
        public static string org_az_32 {
            get {
                return ResourceManager.GetString("org_az_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Girls University.
        /// </summary>
        public static string org_az_33 {
            get {
                return ResourceManager.GetString("org_az_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Cooperation University.
        /// </summary>
        public static string org_az_34 {
            get {
                return ResourceManager.GetString("org_az_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Caspian University.
        /// </summary>
        public static string org_az_35 {
            get {
                return ResourceManager.GetString("org_az_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Higher Military School named after Heydar Aliyev.
        /// </summary>
        public static string org_az_36 {
            get {
                return ResourceManager.GetString("org_az_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Security Service Academy of the Republic of Azerbaijan named after Heydar Aliyev.
        /// </summary>
        public static string org_az_37 {
            get {
                return ResourceManager.GetString("org_az_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ministry of Internal Affairs of the Republic of Azerbaijan, Police Academy.
        /// </summary>
        public static string org_az_38 {
            get {
                return ResourceManager.GetString("org_az_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy of State Border Service of the Republic of Azerbaijan.
        /// </summary>
        public static string org_az_39 {
            get {
                return ResourceManager.GetString("org_az_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku State University.
        /// </summary>
        public static string org_az_4 {
            get {
                return ResourceManager.GetString("org_az_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy of the Ministry of Emergency Situations of Azerbaijan.
        /// </summary>
        public static string org_az_40 {
            get {
                return ResourceManager.GetString("org_az_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief of the Higher Military School of Internal Troops of Ministry of Internal Affairs of Azerbaijan.
        /// </summary>
        public static string org_az_41 {
            get {
                return ResourceManager.GetString("org_az_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy of State Customs Committee of the Republic of Azerbaijan.
        /// </summary>
        public static string org_az_42 {
            get {
                return ResourceManager.GetString("org_az_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku Engineering University.
        /// </summary>
        public static string org_az_5 {
            get {
                return ResourceManager.GetString("org_az_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Oil and Industry University.
        /// </summary>
        public static string org_az_6 {
            get {
                return ResourceManager.GetString("org_az_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Medical University.
        /// </summary>
        public static string org_az_7 {
            get {
                return ResourceManager.GetString("org_az_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan State Economic University.
        /// </summary>
        public static string org_az_8 {
            get {
                return ResourceManager.GetString("org_az_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan University of Architecture and Construction.
        /// </summary>
        public static string org_az_9 {
            get {
                return ResourceManager.GetString("org_az_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - From Azerbaijan.
        /// </summary>
        public static string org_az_side {
            get {
                return ResourceManager.GetString("org_az_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing Committee Members.
        /// </summary>
        public static string org_com {
            get {
                return ResourceManager.GetString("org_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing Committee Members.
        /// </summary>
        public static string org_tr {
            get {
                return ResourceManager.GetString("org_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istanbul University.
        /// </summary>
        public static string org_tr_1 {
            get {
                return ResourceManager.GetString("org_tr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kafkas University.
        /// </summary>
        public static string org_tr_10 {
            get {
                return ResourceManager.GetString("org_tr_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karabuk University.
        /// </summary>
        public static string org_tr_11 {
            get {
                return ResourceManager.GetString("org_tr_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirklareli University.
        /// </summary>
        public static string org_tr_12 {
            get {
                return ResourceManager.GetString("org_tr_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kocaeli University.
        /// </summary>
        public static string org_tr_13 {
            get {
                return ResourceManager.GetString("org_tr_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardahan University.
        /// </summary>
        public static string org_tr_14 {
            get {
                return ResourceManager.GetString("org_tr_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bartin University.
        /// </summary>
        public static string org_tr_15 {
            get {
                return ResourceManager.GetString("org_tr_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonguldak Bülent Ecevit University.
        /// </summary>
        public static string org_tr_16 {
            get {
                return ResourceManager.GetString("org_tr_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzurum Technical University.
        /// </summary>
        public static string org_tr_17 {
            get {
                return ResourceManager.GetString("org_tr_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzurum Ataturk University.
        /// </summary>
        public static string org_tr_18 {
            get {
                return ResourceManager.GetString("org_tr_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazi University.
        /// </summary>
        public static string org_tr_19 {
            get {
                return ResourceManager.GetString("org_tr_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istanbul University (Cerrahpaşa).
        /// </summary>
        public static string org_tr_2 {
            get {
                return ResourceManager.GetString("org_tr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaziantep University.
        /// </summary>
        public static string org_tr_20 {
            get {
                return ResourceManager.GetString("org_tr_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manisa Celal Bayar University.
        /// </summary>
        public static string org_tr_21 {
            get {
                return ResourceManager.GetString("org_tr_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatay Mustafa Kemal University.
        /// </summary>
        public static string org_tr_22 {
            get {
                return ResourceManager.GetString("org_tr_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muş Alparslan University.
        /// </summary>
        public static string org_tr_23 {
            get {
                return ResourceManager.GetString("org_tr_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleyman Demirel University.
        /// </summary>
        public static string org_tr_24 {
            get {
                return ResourceManager.GetString("org_tr_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitit University.
        /// </summary>
        public static string org_tr_25 {
            get {
                return ResourceManager.GetString("org_tr_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anadolu University.
        /// </summary>
        public static string org_tr_26 {
            get {
                return ResourceManager.GetString("org_tr_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozok University.
        /// </summary>
        public static string org_tr_27 {
            get {
                return ResourceManager.GetString("org_tr_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uşak University.
        /// </summary>
        public static string org_tr_28 {
            get {
                return ResourceManager.GetString("org_tr_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacı Bayram Veli University.
        /// </summary>
        public static string org_tr_29 {
            get {
                return ResourceManager.GetString("org_tr_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istanbul Technical University.
        /// </summary>
        public static string org_tr_3 {
            get {
                return ResourceManager.GetString("org_tr_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğu Akdeniz University.
        /// </summary>
        public static string org_tr_30 {
            get {
                return ResourceManager.GetString("org_tr_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karatay University.
        /// </summary>
        public static string org_tr_31 {
            get {
                return ResourceManager.GetString("org_tr_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOK.
        /// </summary>
        public static string org_tr_32 {
            get {
                return ResourceManager.GetString("org_tr_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TİKA.
        /// </summary>
        public static string org_tr_33 {
            get {
                return ResourceManager.GetString("org_tr_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmir Katip Çelebi University.
        /// </summary>
        public static string org_tr_4 {
            get {
                return ResourceManager.GetString("org_tr_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıldız Technical University.
        /// </summary>
        public static string org_tr_5 {
            get {
                return ResourceManager.GetString("org_tr_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akdeniz University.
        /// </summary>
        public static string org_tr_6 {
            get {
                return ResourceManager.GetString("org_tr_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanya Alaaddin Keykubat University.
        /// </summary>
        public static string org_tr_7 {
            get {
                return ResourceManager.GetString("org_tr_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankara University.
        /// </summary>
        public static string org_tr_8 {
            get {
                return ResourceManager.GetString("org_tr_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankara National Defence and Security Institute.
        /// </summary>
        public static string org_tr_9 {
            get {
                return ResourceManager.GetString("org_tr_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - From Turkey.
        /// </summary>
        public static string org_tr_side {
            get {
                return ResourceManager.GetString("org_tr_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Approve.
        /// </summary>
        public static string paper_approve {
            get {
                return ResourceManager.GetString("paper_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paper was approved by our staff!.
        /// </summary>
        public static string paper_approved_text {
            get {
                return ResourceManager.GetString("paper_approved_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Name.
        /// </summary>
        public static string paper_name {
            get {
                return ResourceManager.GetString("paper_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Who Have Sent The Paper:.
        /// </summary>
        public static string paper_send_user {
            get {
                return ResourceManager.GetString("paper_send_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Submission.
        /// </summary>
        public static string paper_submission {
            get {
                return ResourceManager.GetString("paper_submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers.
        /// </summary>
        public static string papers {
            get {
                return ResourceManager.GetString("papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers Of The User.
        /// </summary>
        public static string papers_of_users {
            get {
                return ResourceManager.GetString("papers_of_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Part.
        /// </summary>
        public static string part_1 {
            get {
                return ResourceManager.GetString("part_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Part.
        /// </summary>
        public static string part_2 {
            get {
                return ResourceManager.GetString("part_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Part.
        /// </summary>
        public static string part_3 {
            get {
                return ResourceManager.GetString("part_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Password Is Not Matching!.
        /// </summary>
        public static string pass_not_matching {
            get {
                return ResourceManager.GetString("pass_not_matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string pass_placeholder {
            get {
                return ResourceManager.GetString("pass_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password Must Be At Least 6 Characters Long!.
        /// </summary>
        public static string pass_requirement {
            get {
                return ResourceManager.GetString("pass_requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been sent to your e-mail address.
        /// </summary>
        public static string pass_was_sent {
            get {
                return ResourceManager.GetString("pass_was_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string prev_page {
            get {
                return ResourceManager.GetString("prev_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Of The Conference.
        /// </summary>
        public static string program_conference {
            get {
                return ResourceManager.GetString("program_conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password.
        /// </summary>
        public static string re_password {
            get {
                return ResourceManager.GetString("re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register for submission..
        /// </summary>
        public static string reg_for_submission {
            get {
                return ResourceManager.GetString("reg_for_submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Your registration was successful!.
        /// </summary>
        public static string reg_success {
            get {
                return ResourceManager.GetString("reg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make User (Remove Admin Role).
        /// </summary>
        public static string remove_admin {
            get {
                return ResourceManager.GetString("remove_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE THIS AUTHOR.
        /// </summary>
        public static string remove_author {
            get {
                return ResourceManager.GetString("remove_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter your password.
        /// </summary>
        public static string repass_placeholder {
            get {
                return ResourceManager.GetString("repass_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article should be submitted in one of the languages of Azerbaijani, Turkish or English..
        /// </summary>
        public static string s_req1 {
            get {
                return ResourceManager.GetString("s_req1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference articles which are not approved by the commission will not be commented and manuscripts will not be returned back..
        /// </summary>
        public static string s_req10 {
            get {
                return ResourceManager.GetString("s_req10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author is responsible for the information and facts contained in the text..
        /// </summary>
        public static string s_req11 {
            get {
                return ResourceManager.GetString("s_req11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted articles to be published in the “Conference Proceedings”..
        /// </summary>
        public static string s_req12 {
            get {
                return ResourceManager.GetString("s_req12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference articles should be in a two-column-built-set and should not exceed the volume of 6 pages..
        /// </summary>
        public static string s_req13 {
            get {
                return ResourceManager.GetString("s_req13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the beginning of the article, key words and an abstract of 50-100 words in 2 languages (in which the article is compiled and in one of the other languages of the conference) should be provided..
        /// </summary>
        public static string s_req14 {
            get {
                return ResourceManager.GetString("s_req14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article must be prepared in MS Word program in A4 format (left and right – 2 cm, top and bottom – 2.5 cm), 12 point in Times New Roman font, 1.0 interlinear interval and text inside inscription 1 cm..
        /// </summary>
        public static string s_req2 {
            get {
                return ResourceManager.GetString("s_req2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article should be prepared in the following sequence: author/s&apos; full name – in the middle; author/s&apos; work place, city and country – in the middle, at the end 6 point intervals (if the authors represent different organizations, the names of the authors and the organizations are numbered with the upper index); the title of the article – in capital letters, bold font, centered; at the end 6 point intervals, e-mail address..
        /// </summary>
        public static string s_req3 {
            get {
                return ResourceManager.GetString("s_req3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References: name of each reference is numbered according to the sequence of their use in the article, without translating..
        /// </summary>
        public static string s_req4 {
            get {
                return ResourceManager.GetString("s_req4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table and figures are numbered in the article: table title at the top of the table and from the right side (for ex.: Table 1), figure title below of the figure and centered (for ex.: Figure 1), and the text is displayed with a blank line (top and bottom), leaving 1 (one) blank line..
        /// </summary>
        public static string s_req5 {
            get {
                return ResourceManager.GetString("s_req5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical expressions are compiled by using the formula editor of MS Word programme (Equation). Only the formulas used in the text are numbered. Formula is written in the middle of the line and the number is written in brackets on the right..
        /// </summary>
        public static string s_req6 {
            get {
                return ResourceManager.GetString("s_req6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the article is sent to the conference, information about the authors: full name, scientific degree, academic title, place of work, position, phone number, title of the abstract, section number and title of the conference are provided in e-mail..
        /// </summary>
        public static string s_req7 {
            get {
                return ResourceManager.GetString("s_req7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article will electronically be sent to one of the conference addresses:.
        /// </summary>
        public static string s_req8 {
            get {
                return ResourceManager.GetString("s_req8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each article is reviewed by the members of the Organizing Committee..
        /// </summary>
        public static string s_req9 {
            get {
                return ResourceManager.GetString("s_req9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Secretary of the Conference.
        /// </summary>
        public static string sci_sec {
            get {
                return ResourceManager.GetString("sci_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Subhan Namazov – Vice-Rector of Azerbaijan Technical University on International Relations.
        /// </summary>
        public static string sci_secretary {
            get {
                return ResourceManager.GetString("sci_secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Paper.
        /// </summary>
        public static string search_paper {
            get {
                return ResourceManager.GetString("search_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        public static string search_user {
            get {
                return ResourceManager.GetString("search_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string sponsors {
            get {
                return ResourceManager.GetString("sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Your file uploaded successfully!.
        /// </summary>
        public static string sub_success {
            get {
                return ResourceManager.GetString("sub_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        public static string submission {
            get {
                return ResourceManager.GetString("submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIREMENTS FOR THE CONFERENCE MATERIALS (ABSTRACT AND FULL-TEXT).
        /// </summary>
        public static string submission_requirements {
            get {
                return ResourceManager.GetString("submission_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the Paper.
        /// </summary>
        public static string submit_title {
            get {
                return ResourceManager.GetString("submit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The maximum number of characters allowed is 200):.
        /// </summary>
        public static string submit_title_max {
            get {
                return ResourceManager.GetString("submit_title_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT YOUR PAPER.
        /// </summary>
        public static string submit_your_paper {
            get {
                return ResourceManager.GetString("submit_your_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this paper?.
        /// </summary>
        public static string sure_to_remove {
            get {
                return ResourceManager.GetString("sure_to_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        public static string title_1 {
            get {
                return ResourceManager.GetString("title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        public static string title_2 {
            get {
                return ResourceManager.GetString("title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        public static string title_3 {
            get {
                return ResourceManager.GetString("title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Lecturer.
        /// </summary>
        public static string title_4 {
            get {
                return ResourceManager.GetString("title_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhD Candidate.
        /// </summary>
        public static string title_5 {
            get {
                return ResourceManager.GetString("title_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        public static string title_6 {
            get {
                return ResourceManager.GetString("title_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Professor.
        /// </summary>
        public static string title_7 {
            get {
                return ResourceManager.GetString("title_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string title_8 {
            get {
                return ResourceManager.GetString("title_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical and technological sciences.
        /// </summary>
        public static string topic_1 {
            get {
                return ResourceManager.GetString("topic_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics and math.
        /// </summary>
        public static string topic_2 {
            get {
                return ResourceManager.GetString("topic_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanities and social sciences.
        /// </summary>
        public static string topic_3 {
            get {
                return ResourceManager.GetString("topic_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine, biology and chemistry.
        /// </summary>
        public static string topic_4 {
            get {
                return ResourceManager.GetString("topic_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education, training technologies and pedagogy.
        /// </summary>
        public static string topic_5 {
            get {
                return ResourceManager.GetString("topic_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic sciences.
        /// </summary>
        public static string topic_6 {
            get {
                return ResourceManager.GetString("topic_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction and architectural sciences.
        /// </summary>
        public static string topic_7 {
            get {
                return ResourceManager.GetString("topic_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conference is soliciting state-of-the-art research papers in the following areas of interest.
        /// </summary>
        public static string topic_title {
            get {
                return ResourceManager.GetString("topic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string topics {
            get {
                return ResourceManager.GetString("topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users From Turkey Who Sent The Paper.
        /// </summary>
        public static string tr_paper_users {
            get {
                return ResourceManager.GetString("tr_paper_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string uploaded {
            get {
                return ResourceManager.GetString("uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users&apos; Information.
        /// </summary>
        public static string user_info {
            get {
                return ResourceManager.GetString("user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide A Valid Email!.
        /// </summary>
        public static string valid_email {
            get {
                return ResourceManager.GetString("valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide A Valid Password!.
        /// </summary>
        public static string valid_pass {
            get {
                return ResourceManager.GetString("valid_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide A Valid Phone!.
        /// </summary>
        public static string valid_phone {
            get {
                return ResourceManager.GetString("valid_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide A Valid Value!.
        /// </summary>
        public static string valid_value {
            get {
                return ResourceManager.GetString("valid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string venue {
            get {
                return ResourceManager.GetString("venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Technical University (AzTU) is one of the leading universities in the field of technical education of Azerbaijan Republic, which was established as Azerbaijan Polytechnic Institute in 1950. With about 7000 students, AzTU offers education in BA, MA and PhD degrees in several areas of study. There are about 30 bachelor&apos;s degree specialties and up to 100 master’s degree specialties at AzTU. Currently the university trains highly qualified specialists in the following faculties:.
        /// </summary>
        public static string venue_text_1 {
            get {
                return ResourceManager.GetString("venue_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are a Scientific-research centre and 6 specialized laboratories for students and employees. The languages of instruction at AzTU are Azerbaijani and Russian. Around 650 academic and administrative staff including more than 70 professors, doctors of sciences, around 350 associate professors, candidate of science (PhD) work at 35 chairs of faculties. The results of scientific achievements of the University are published in the scientific-technical journal “Scientific works” and &quot;Mechanical Engineering&quot;. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string venue_text_10 {
            get {
                return ResourceManager.GetString("venue_text_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzTU has developed strong academic relations within the framework of various international projects. Our university collaborates with UN, UNESKO, TRASEKA and other relevant International Organisations and a lot of foreign universities. The University has direct contacts with the most leading universities of USA, Germany, France, Korea, Turkey, Romania, Russia, Ukraine, Belarus, Latvia, Kazakhstan. According to UniRank World University 2018 Rankings, AzTU is ranked 6341 and No 6 in country rank..
        /// </summary>
        public static string venue_text_11 {
            get {
                return ResourceManager.GetString("venue_text_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string venue_text_2 {
            get {
                return ResourceManager.GetString("venue_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical engineering and energetics.
        /// </summary>
        public static string venue_text_3 {
            get {
                return ResourceManager.GetString("venue_text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio engineering and communication.
        /// </summary>
        public static string venue_text_4 {
            get {
                return ResourceManager.GetString("venue_text_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallurgy.
        /// </summary>
        public static string venue_text_5 {
            get {
                return ResourceManager.GetString("venue_text_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical engineering.
        /// </summary>
        public static string venue_text_6 {
            get {
                return ResourceManager.GetString("venue_text_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation and computer engineering.
        /// </summary>
        public static string venue_text_7 {
            get {
                return ResourceManager.GetString("venue_text_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special techniques and technology.
        /// </summary>
        public static string venue_text_8 {
            get {
                return ResourceManager.GetString("venue_text_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering business and management.
        /// </summary>
        public static string venue_text_9 {
            get {
                return ResourceManager.GetString("venue_text_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice-Chairs of the Conference.
        /// </summary>
        public static string vise_chairs {
            get {
                return ResourceManager.GetString("vise_chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Ilham Pirmammadov – Vice-Rector of Azerbaijan Technical University on Science and Technics.
        /// </summary>
        public static string vise_chairs_1 {
            get {
                return ResourceManager.GetString("vise_chairs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Subhan Namazov – Vice-Rector of Azerbaijan Technical University on International Relations.
        /// </summary>
        public static string vise_chairs_2 {
            get {
                return ResourceManager.GetString("vise_chairs_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Dr. Ahmet Kemal Çelebi – Rector of Manisa Celal Bayar University.
        /// </summary>
        public static string vise_chairs_3 {
            get {
                return ResourceManager.GetString("vise_chairs_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we upload your file.
        /// </summary>
        public static string wait_until_download {
            get {
                return ResourceManager.GetString("wait_until_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string your_pass {
            get {
                return ResourceManager.GetString("your_pass", resourceCulture);
            }
        }
    }
}
