//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aztuKonfrans2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Paper_Author = new HashSet<Paper_Author>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public Nullable<byte> title_id { get; set; }
        public Nullable<byte> degree_id { get; set; }
        public Nullable<byte> country_id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string institution { get; set; }
        public string position { get; set; }
        public Nullable<byte> isVisible { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<Paper_Author> Paper_Author { get; set; }
    }
}
