//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aztuKonfrans2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper_Author
    {
        public int id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> paper_id { get; set; }
        public Nullable<byte> isVisible { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
