//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aztuKonfrans2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Papers = new HashSet<Paper>();
            this.Users = new HashSet<User>();
        }
    
        public byte id { get; set; }
    
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
