//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aztuKonfrans2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Papers = new HashSet<Paper>();
        }
    
        public short id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<byte> country_id { get; set; }
        public Nullable<byte> title_id { get; set; }
        public Nullable<byte> degree_id { get; set; }
        public Nullable<byte> topic_id { get; set; }
        public Nullable<byte> role_id { get; set; }
        public string institution { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual Role Role { get; set; }
        public virtual Title Title { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
